export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";


export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";